import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outputPath = resolve(__dirname, '../src/environments/api-url.generated.ts');
const rawApiUrl = process.env.BACKEND_API_URL || process.env.NG_APP_API_URL || '/api/v1';
const apiUrl = rawApiUrl.replace(/\/+$/, '');

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(
  outputPath,
  `// Generated by scripts/write-api-url.mjs during the frontend build.\nexport const generatedApiUrl = ${JSON.stringify(apiUrl)};\n`,
  'utf8'
);

console.log(`Using API URL: ${apiUrl}`);
